[
  ./mysql.nix
  ./redis.nix
  ./elasticsearch.nix
  ./curator.nix
  ./gitlab.nix
  ./gitlab-runner.nix
  ./pritunl.nix
  ./openvpn.nix
  ./nginxingress.nix
  ./mediawiki.nix
  ./influxdb.nix
  ./grafana.nix
  ./kibana.nix
  ./nfs.nix
  ./crossbar.nix
  ./global.nix
  ./rabbitmq.nix
  ./sinopia.nix
  ./logstash.nix
  ./kubelog.nix
  ./kapacitor.nix
  ./telegraf.nix
  ./tick.nix
  ./heapster.nix
  ./vault.nix
  ./aws-es-kibana.nix
  ./kube-lego.nix
  ./taskd.nix
  ./mongodb.nix
  ./rippled.nix
  ./mediawiki-query-service.nix
  ./tor.nix
  ./etcd.nix
  ./parity.nix
]
