[
  ./mysql.nix
  ./redis.nix
  ./elasticsearch.nix
  ./curator.nix
  ./gitlab.nix
  ./gitlab-runner.nix
  ./pritunl.nix
  ./openvpn.nix
  ./nginx-ingress.nix
  ./mediawiki.nix
  ./influxdb.nix
  ./grafana.nix
  ./kibana.nix
  ./nfs.nix
  ./crossbar.nix
  ./global.nix
  ./rabbitmq.nix
  ./sinopia.nix
  ./logstash.nix
  ./kubelog.nix
  ./kapacitor.nix
  ./tick.nix
  ./heapster.nix
  ./vault.nix
]
